# Generated by Django 4.0.4 on 2023-12-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonfeatures',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
