# Generated by Django 4.0.4 on 2023-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_email_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Last Name'),
        ),
    ]
